name: CD - Despliegue en Render

on:
  workflow_run:
    workflows: ["CI - Build and Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Añadir permisos para que este workflow pueda activar otro
    #n
    permissions:
      actions: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Desplegar en Render y verificar estado
        id: deploy
        run: |
          # Iniciar el despliegue y capturar el código de estado HTTP
          http_status=$(curl --request POST \
            --url "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            --header "Accept: application/json" \
            --header "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            --data '{}' \
            --output response.json \
            --write-out "%{http_code}")
          
          deploy_response=$(cat response.json)
          
          if [ "$http_status" -ne 201 ]; then
            echo "Error: La API de Render devolvió un código de estado HTTP $http_status."
            echo "Respuesta de la API: $deploy_response"
            exit 1
          fi
          
          deploy_id=$(echo "$deploy_response" | jq -r '.id')
          
          if [ -z "$deploy_id" ] || [ "$deploy_id" == "null" ]; then
            echo "Error al iniciar el despliegue. Respuesta de la API:"
            echo "$deploy_response"
            exit 1
          fi
          
          echo "Despliegue iniciado con ID: $deploy_id"
          
          # Esperar y verificar el estado del despliegue en un bucle
          while true; do
            sleep 30
            deploy_status=$(curl -s --request GET \
              --url "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys/$deploy_id" \
              --header "Accept: application/json" \
              --header "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" | jq -r '.status')
            
            echo "Estado actual del despliegue: $deploy_status"
            
            if [ "$deploy_status" == "live" ]; then
              echo "Despliegue exitoso."
              break
            elif [ "$deploy_status" == "build_failed" ] || [ "$deploy_status" == "canceled" ] || [ "$deploy_status" == "deactivated" ]; then
              echo "El despliegue ha fallado con estado: $deploy_status"
              exit 1
            fi
          done

      - name: Disparar Rollback si el despliegue falló
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            console.log('El despliegue ha fallado. Iniciando el workflow de rollback...');
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'rollback.yml',
              ref: 'main'
            })
